-- Question 1

SELECT STORE_NAME as "Store", sum(T.SALE) as "Highest Sales" FROM DW.TRANSACTIONS T 
		 JOIN STORE S 
         ON T.STORE_ID = S.STORE_ID
         JOIN TIME_d F ON T.TIME_ID = F.TIME_ID 
         WHERE F.T_MONTH = "september" AND F.T_YEAR = 2017
         GROUP BY STORE_NAME 
         ORDER BY "Highest Sales" DESC 
         LIMIT 3;


-- Question 2
SELECT SUPPLIER_NAME as "Supplier" ,SUM(SALE) AS Revenue FROM TRANSACTIONS T
		JOIN SUPPLIER S 
        ON T.SUPPLIER_ID = S.SUPPLIER_ID
        JOIN TIME_d F
        ON T.TIME_ID = F.TIME_ID
        WHERE F.T_DAY IN ('Saturday' , 'Sunday')
        GROUP BY T.SUPPLIER_ID
        ORDER BY Revenue DESC
        LIMIT 10;


-- Question 3
SELECT SUPPLIER_NAME as "Supplier", F.T_MONTH AS "MONTH", F.T_QUARTER AS "QUARTER", SUM(SALE) AS "SALES" FROM TRANSACTIONS T 
		JOIN PRODUCTS P
        ON T.PRODUCT_ID = P.PRODUCT_ID
        JOIN SUPPLIER S
        ON T.SUPPLIER_ID = S.SUPPLIER_ID
        JOIN TIME_d F
        ON T.TIME_ID = F.TIME_ID
        GROUP BY T.SUPPLIER_ID , QUARTER ,MONTH WITH ROLLUP
        ORDER BY SUPPLIER_NAME,QUARTER,MONTH ASC;

-- Question 4
        SELECT S.STORE_NAME,P.PRODUCT_NAME , SUM(T.SALE) AS SALE 
        FROM TRANSACTIONS T, PRODUCTS P, STORE S
        WHERE P.PRODUCT_ID = T.PRODUCT_ID and S.STORE_ID = T.STORE_ID
        GROUP BY  S.STORE_NAME,P.PRODUCT_NAME
		ORDER BY S.STORE_NAME;


-- Question 5
 
SELECT STORE_NAME as "Store",F.T_QUARTER AS "QUARTER", SUM(SALE) AS SALE FROM TRANSACTIONS T
		JOIN STORE S
        ON T.STORE_ID = S.STORE_ID
        JOIN TIME_d F
        ON T.TIME_ID = F.TIME_ID
        GROUP BY STORE_NAME,QUARTER WITH ROLLUP;

-- Question 6
SELECT T.PRODUCT_ID,PRODUCT_NAME,sum(T.Quantity) AS "TOTAL" FROM DW.TRANSACTIONS T 
		 JOIN PRODUCTS P 
         ON T.PRODUCT_ID = P.PRODUCT_ID
         JOIN TIME_d F
         ON T.TIME_ID = F.TIME_ID 
         WHERE T_DAY IN ('Saturday' , 'Sunday')
         GROUP BY P.PRODUCT_NAME 
         ORDER BY TOTAL DESC 
         LIMIT 5;

-- Question 7
SELECT STORE_NAME,SUPPLIER_NAME,PRODUCT_NAME ,SUM(SALE) AS TOTAL FROM TRANSACTIONS T
		JOIN STORE S
        ON T.STORE_ID = S.STORE_ID
        JOIN PRODUCTS P
        ON T.PRODUCT_ID = P.PRODUCT_ID
        JOIN SUPPLIER SR
        ON T.SUPPLIER_ID = SR.SUPPLIER_ID
        GROUP BY STORE_NAME,SUPPLIER_NAME,PRODUCT_NAME WITH ROLLUP;

-- Question 9
SELECT * FROM PRODUCTS
GROUP BY PRODUCT_NAME
HAVING COUNT(PRODUCT_NAME)>1;


-- Question 10
	CREATE VIEW STORE_PRODUCT_ANALYSIS AS
    SELECT STORE_NAME AS "Store", PRODUCT_NAME as "Product", SUM(SALE) AS SALES
    FROM TRANSACTIONS T
    JOIN PRODUCTS P 
    ON T.PRODUCT_ID = P.PRODUCT_ID
	JOIN STORE S
	ON T.STORE_ID = S.STORE_ID 
    GROUP BY STORE_NAME,PRODUCT_NAME WITH ROLLUP;
    SELECT * FROM STORE_PRODUCT_ANALYSIS;
    DROP VIEW STORE_PRODUCT_ANALYSIS;


